apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: mysql-backup
spec:
  schedule: "*/10 * * * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template: 
        spec: 
          containers:
            - name: mysql-backup
              image: gcr.io/epam-001/mysql-backup2:1.0.5
              command: 
                - sh 
                - /root/backup-script.sh
              env:
              - name: DB_HOST
                value: clouddb
              - name: DB_USER
                valueFrom:
                  secretKeyRef:
                      name: sql-info
                      key: user
              - name: DB_PASS
                valueFrom:
                  secretKeyRef:
                    name: sql-info
                    key: password
              - name: DB_NAME
                value: gcp_training
              - name: GS_BUCKET
                value: epam-demobk 
          restartPolicy: Never